### PR TITLE
Adds envoy-versions.json and its schema

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Follow-up from https://github.com/tetratelabs/getenvoy/pull/281

This is not fully automated yet, intentionally

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
deploy preview doesn't seem top redirect properly.. will look into it tomorrow

**Comment by codefromthecrypt** [comment]
ok works now

```bash
$ ENVOY_VERSIONS_URL=https://deploy-preview-2--archive-envoy.netlify.app/envoy-versions.json
$ getenvoy versions -a
VERSION	RELEASE_DATE
1.18.3	2021-05-11
1.17.3	2021-05-11
1.16.4	2021-05-11
1.15.5	2021-05-11
1.16.3	2021-04-15
1.14.7	2021-04-15
1.13.7	2020-12-07
1.12.7	2020-09-29
$ ENVOY_VERSION=1.13.7 getenvoy run --version
looking up latest version
downloading https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.13.7.p0.g56d148b-1p70.g486d4e2-darwin-release-x86_64.tar.xz
starting: /Users/adrian/.getenvoy/versions/1.13.7/bin/envoy --version
working directory: /Users/adrian/.getenvoy/runs/1623843261785475000

/Users/adrian/.getenvoy/versions/1.13.7/bin/envoy  version: 56d148b94ef25a026d8d31790695d478ad53eb94/1.13.7/clean-getenvoy-486d4e2-envoy/RELEASE/BoringSSL
```

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
will rework this a little so that the envoy-versions.json file is checked on PR

**Comment by codefromthecrypt** [comment]
I'm going to merge this because it isn't released yet. there's some cache I can't clear and I think it will work mostly :D

**Comment by mathetake** [comment]
image

**Pull request merged**
